### ISSUE TITLE
Nifti not a 4D volume

### ISSUE THREAD

**Issue by srithetree** [smoia/phys2cvr#51]
Input parameter is a 4D BOLD functional nifti file but it does not recognize it as 4 dimensional.

## Expected Behavior

One would expect it to recognize it as 4D and continue to regression.

## Actual Behavior

It stops and provides the error: "ValueError: Provided functional file /home/sri/CVR/derivatives/fmriprep/sub-scd026/ses-02/func/sub-scd026_ses-02_task-cvr_desc-preproc_bold.nii.gz is not a 4D file!"

Full error output:
phys2cvr -i /home/sri/CVR/derivatives/fmriprep/sub-scd026/ses-02/func/sub-scd026_ses-02_task-cvr_desc-preproc_bold.nii.gz -o /home/sri/CVR/sri/test -m /home/sri/CVR/derivatives/fmriprep/sub-scd026/ses-02/func/sub-scd026_ses-02_task-cvr_desc-brain_mask.nii.gz -co2 /home/sri/CVR/sri/scd026_co2.csv -pk /home/sri/CVR/sri/scd026_co2_pidx.csv -fr 95.051 -tlen 19.78 -ntrial 5
INFO       Currently running phys2cvr version 0.15.0
INFO       Input file is /home/sri/CVR/derivatives/fmriprep/sub-scd026/ses-02/func/sub-scd026_ses-02_task-cvr_desc-preproc_bold.nii.gz
WARNING    Changing type of variable trial_len from <class 'float'> to int
INFO       Loading /home/sri/CVR/derivatives/fmriprep/sub-scd026/ses-02/func/sub-scd026_ses-02_task-cvr_desc-preproc_bold.nii.gz
WARNING    /home/sri/CVR/derivatives/fmriprep/sub-scd026/ses-02/func/sub-scd026_ses-02_task-cvr_desc-preproc_bold.nii.gz has more than 3 dimensions. Removing D > 3.
Traceback (most recent call last):
  File "/net/rc-fs-nfs.tch.harvard.edu/ifs/RC-FS-PROD/Data/Shares/FNNDSC-e2/neuro/labs/grantlab/research/CVR/venv/bin/phys2cvr", line 8, in <module>
    sys.exit(_main())
  File "/net/rc-fs-nfs.tch.harvard.edu/ifs/RC-FS-PROD/Data/Shares/FNNDSC-e2/neuro/labs/grantlab/research/CVR/venv/lib/python3.8/site-packages/phys2cvr/phys2cvr.py", line 606, in _main
    phys2cvr(**vars(options))
  File "/net/rc-fs-nfs.tch.harvard.edu/ifs/RC-FS-PROD/Data/Shares/FNNDSC-e2/neuro/labs/grantlab/research/CVR/venv/lib/python3.8/site-packages/phys2cvr/phys2cvr.py", line 278, in phys2cvr
    raise ValueError(f'Provided functional file {fname_func} is not a 4D file!')
ValueError: Provided functional file /home/sri/CVR/derivatives/fmriprep/sub-scd026/ses-02/func/sub-scd026_ses-02_task-cvr_desc-preproc_bold.nii.gz is not a 4D file!

## Steps to Reproduce the Problem

    1. Give it this path and run the command
    2.
    3.

## Specifications

    - Python version: 
    - phys2bids version:
    - Platform:

**Comment by dittothat** [comment]
Hi Stefano,
Sri is a medical student intern working with me this summer. I looked at this with him a bit, and on first glance at the underlying code don't know why https://github.com/smoia/phys2cvr/blob/6713a5dd3b0ddb42698c1906f50121423dd7ba07/phys2cvr/phys2cvr.py#L276 is left to default of dim=3.
Thanks, Jeff
