### ISSUE TITLE
Possible problem in bandpass filtering

### ISSUE THREAD

**Issue by farnazdelavari** [smoia/phys2cvr#89]
I have been trying to generate CVR maps for simple resting state fMRI. The filtered average signal which is an output from the toolbox (petco2hrf) looked a bit strange to me. When checking the spectral density, it seems to us that the filtering might have failed. 
## Expected Behavior

I would expect such time-course: 
![image_2023-08-09_17-49-24](https://github.com/smoia/phys2cvr/assets/48866546/cdfa8a60-b4dd-4e4b-8196-f55e81b179b2)

and a  high density within the filtered 0.02-0.04 range of the filtered time course. 
![image_2023-08-09_17-48-32](https://github.com/smoia/phys2cvr/assets/48866546/81d26f8a-af11-475a-a22d-7d80ccdd93b1)

## Actual Behavior

The toolbox time-course is as below 
![image_2023-08-09_17-49-35](https://github.com/smoia/phys2cvr/assets/48866546/aaf6c313-b5e9-4b12-a899-cd2aa12630d1)

with the spectral density that is different : 
![image_2023-08-09_17-50-02](https://github.com/smoia/phys2cvr/assets/48866546/aa2ea69a-1587-4bec-bc16-437c87d9d544)

## Steps to Reproduce the Problem

If the tc is the time-course filtered and stored in "avg_func_masked_petco2hrf.1D" and TR is the sampling rate of the MRI in seconds. 
then this code in Matlab should generate the spectral density as stated. 
N=lenghth(tc);
fs=1/TR;
xdft=fft(tc);
xdft = xdft(1:N/2+1);
psdx = (1/(fs*N)) * abs(xdft).^2;
psdx(2:end-1) = 2*psdx(2:end-1);
freq = 0:fs/N:fs/2;
figure
plot(freq,pow2db(psdx),'r')

## Specifications

    - phys2cvr version: 0.16.0

    - resting-state fMRI, TR=2.4 s, number of volumes = 200, band used = 0.02-0.04.

**Comment by smoia** [comment]
@farnazdelavari can you check the new version against your matlab code please?
